#!/bin/sh

# Refresh repos otherwise installations later may fail
apt-get update

# Install HTTPS transport
apt-get -y install apt-transport-https

# Install some more fonts
apt-get -y install fonts-open-sans

# Install gnupg2
apt-get -y install gnupg2

# install ca-certificates
apt-get -y install ca-certificates

# install ssh-keygen binary for the WOPI proof key
apt-get -y install openssh-client

# Install curl for simple healthchecks
apt-get -y install curl

# Add Collabora repos
echo "deb https://collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu1804 /" > /etc/apt/sources.list.d/collabora.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6CCEA47B2281732DF5D504D00C54D189F4BA284D
apt-get update

# Install the Collabora packages
apt-get -y install loolwsd code-brand collaboraoffice6.4-dict* collaboraofficebasis6.4-ar collaboraofficebasis6.4-as collaboraofficebasis6.4-ast collaboraofficebasis6.4-bg collaboraofficebasis6.4-bn-in collaboraofficebasis6.4-br collaboraofficebasis6.4-ca collaboraofficebasis6.4-calc collaboraofficebasis6.4-ca-valencia collaboraofficebasis6.4-core collaboraofficebasis6.4-cs collaboraofficebasis6.4-cy collaboraofficebasis6.4-da collaboraofficebasis6.4-de collaboraofficebasis6.4-draw collaboraofficebasis6.4-el collaboraofficebasis6.4-en-gb collaboraofficebasis6.4-en-us collaboraofficebasis6.4-es collaboraofficebasis6.4-et collaboraofficebasis6.4-eu collaboraofficebasis6.4-extension-pdf-import collaboraofficebasis6.4-fi collaboraofficebasis6.4-fr collaboraofficebasis6.4-ga collaboraofficebasis6.4-gd collaboraofficebasis6.4-gl collaboraofficebasis6.4-graphicfilter collaboraofficebasis6.4-gu collaboraofficebasis6.4-he collaboraofficebasis6.4-hi collaboraofficebasis6.4-hr collaboraofficebasis6.4-hu collaboraofficebasis6.4-id collaboraofficebasis6.4-images collaboraofficebasis6.4-impress collaboraofficebasis6.4-is collaboraofficebasis6.4-it collaboraofficebasis6.4-ja collaboraofficebasis6.4-km collaboraofficebasis6.4-kn collaboraofficebasis6.4-ko collaboraofficebasis6.4-lt collaboraofficebasis6.4-lv collaboraofficebasis6.4-ml collaboraofficebasis6.4-mr collaboraofficebasis6.4-nb collaboraofficebasis6.4-nl collaboraofficebasis6.4-nn collaboraofficebasis6.4-oc collaboraofficebasis6.4-ooofonts collaboraofficebasis6.4-ooolinguistic collaboraofficebasis6.4-or collaboraofficebasis6.4-pa-in collaboraofficebasis6.4-pl collaboraofficebasis6.4-pt collaboraofficebasis6.4-pt-br collaboraofficebasis6.4-ro collaboraofficebasis6.4-ru collaboraofficebasis6.4-sk collaboraofficebasis6.4-sl collaboraofficebasis6.4-sr collaboraofficebasis6.4-sr-latn collaboraofficebasis6.4-sv collaboraofficebasis6.4-ta collaboraofficebasis6.4-te collaboraofficebasis6.4-tr collaboraofficebasis6.4-uk collaboraofficebasis6.4-vi collaboraofficebasis6.4-writer collaboraofficebasis6.4-zh-cn collaboraofficebasis6.4-zh-tw

# Install inotifywait and killall to automatic restart loolwsd, if loolwsd.xml changes
apt-get -y install inotify-tools psmisc

# Cleanup
rm -rf /var/lib/apt/lists/*

# Remove WOPI Proof key generated by the package, we need unique key for each container
rm -rf /etc/loolwsd/proof_key*

# Fix permissions
chown -R lool:lool /opt/
chown -R lool:lool /etc/loolwsd
